import os
import glob
from functools import partial
from collections import defaultdict

# sanity check; exit early if paths are not set properly
ROOT = config['root'] or os.getenv('ROOT')
if not ROOT:
  print("Project ROOT not set. Check config. Exiting.")
  exit(1)

data = partial(os.path.join, ROOT, 'data')
work = partial(os.path.join, ROOT, 'work')

#
# contains list of target output files 
FINAL = [] 

# extend output
# for example,
#
# FINAL.extend(
#    ['tmp.py', 'hello.py']
# )

#
# main rule, specify list of files to be generated
rule all:
  input:
    FINAL

# sub-rules


# Snakemake notification
onerror:
  print("Error: Snakemake aborted!")
  shell("mail -s 'Snakemake Job Error: See log inside!' {config[email]} < {log}")


onsuccess:
  print("Success: Snakemake completed!")
  shell("mail -s 'Snakemake Job Completed: Have a Beer!' {config[email]} < {log}")

# vim: syntax=snakemake
